services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic 

networks:
  elastic:
    driver: bridge
