version: '3'
services:
  attacker1:
    image: ubuntu:latest
    command: sleep infinity
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      attack_network:
        ipv4_address: 172.20.0.1

  attacker2:
    image: ubuntu:latest
    command: sleep infinity
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      attack_network:
        ipv4_address: 172.20.0.2

  attacker3:
    image: ubuntu:latest
    command: sleep infinity
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      attack_network:
        ipv4_address: 172.20.0.3

  attacker4:
    image: ubuntu:latest
    command: sleep infinity
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      attack_network:
        ipv4_address: 172.20.0.4

  attacker5:
    image: ubuntu:latest
    command: sleep infinity
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      attack_network:
        ipv4_address: 172.20.0.5

  attacker6:
    image: ubuntu:latest
    command: sleep infinity
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      attack_network:
        ipv4_address: 172.20.0.6

  attacker7:
    image: ubuntu:latest
    command: sleep infinity
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      attack_network:
        ipv4_address: 172.20.0.7

  attacker8:
    image: ubuntu:latest
    command: sleep infinity
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      attack_network:
        ipv4_address: 172.20.0.8

  attacker9:
    image: ubuntu:latest
    command: sleep infinity
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      attack_network:
        ipv4_address: 172.20.0.9

  attacker10:
    image: ubuntu:latest
    command: sleep infinity
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      attack_network:
        ipv4_address: 172.20.0.10

networks:
  attack_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24